/// plang_time.cpp — Pascal TimeStamp type and date/time functions (EP §6.4.3.4)

#include <cinttypes>
#include <cstdint>
#include <cstdio>
#include <ctime>

namespace plang {

/// Mirrors the Pascal TimeStamp record layout generated by Sema.
/// Fields match: DateValid(i8), year(i64), month(i64), day(i64),
///               TimeValid(i8), hour(i64), minute(i64), second(i64).
/// Layout is determined by the LLVM struct { i8, i64, i64, i64, i8, i64, i64, i64 }.
struct PlangTimeStamp {
    int8_t  DateValid;
    int64_t year, month, day;
    int8_t  TimeValid;
    int64_t hour, minute, second;
};

extern "C" {

/// EP §6.7.5.8: fill a TimeStamp variable with the current local date and time.
void plang_gettimestamp(PlangTimeStamp* T) {
    std::time_t now = std::time(nullptr);
    std::tm* tm = std::localtime(&now);
    if (tm) {
        T->DateValid = 1;
        T->year      = 1900 + tm->tm_year;
        T->month     = 1    + tm->tm_mon;
        T->day       = tm->tm_mday;
        T->TimeValid = 1;
        T->hour      = tm->tm_hour;
        T->minute    = tm->tm_min;
        T->second    = tm->tm_sec;
    } else {
        // §6.7.5.8: the false-DateValid fallback is "the date 'January 1, 1'",
        // not an all-zero non-date -- day/month/year=0 is not even a value
        // the record's own field bounds (1..31, 1..12) permit.
        T->DateValid = 0;
        T->year = 1; T->month = 1; T->day = 1;
        T->TimeValid = 0;
        T->hour = T->minute = T->second = 0;
    }
}

/// EP §6.7.6.9: format the date portion of a TimeStamp as "YYYY-MM-DD".
/// Returns a pointer to a static buffer (Pascal programs are single-threaded).
const char* plang_date(const PlangTimeStamp* T) {
    // date(t) is specified purely as a function of day/month/year -- DateValid
    // never appears in its contract, only in GetTimeStamp's.  It gated on
    // DateValid and printed a fixed "0000-00-00" instead, discarding whatever
    // the fields actually held (which GetTimeStamp guarantees is always a
    // valid date, DateValid true or false).
    static char buf[16];
    std::snprintf(buf, sizeof(buf), "%04" PRId64 "-%02" PRId64 "-%02" PRId64,
                  T->year, T->month, T->day);
    return buf;
}

/// EP §6.7.6.9: format the time portion of a TimeStamp as "HH:MM:SS".
const char* plang_time_ts(const PlangTimeStamp* T) {
    // Same fix as plang_date, for the identical reason: time(t) is specified
    // purely as a function of hour/minute/second, not gated on TimeValid.
    static char buf[12];
    std::snprintf(buf, sizeof(buf), "%02" PRId64 ":%02" PRId64 ":%02" PRId64,
                  T->hour, T->minute, T->second);
    return buf;
}

} // extern "C"

} // namespace plang
