// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0201) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 201: Missing first field ident

}

program iso7185prt0201;

var a: record , c: integer end;

begin

   a.c := 1

end.
)plang").Ok);
}
