// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0306) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 306: Missing type ident after ':' for function

}

program iso7185prt0306;

function x(one, two: integer):;

begin

   one := 1;
   two := 2;
   x := 'a'

end;

begin

end.
)plang").Ok);
}
