// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0904) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 904: Missing second parameter in parameter list

}

program iso7185prt0904(output);

begin

    
   write(42, )

end.
)plang").Ok);
}
