// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0603) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 603: Missing ',' between parameter identifiers

}

program iso7185prt0603;

procedure a(b c: integer);

begin

   b := 1;
   c := 1

end;

begin

   a(1, 2)

end.
)plang").Ok);
}
