// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0133) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 133: Misspelled "until" on repeat statement

}

program iso7185prt0133;

var a, b: integer;

begin

   repeat a := b util a = b

end.
)plang").Ok);
}
