// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0716) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 716: Alternate '=>'

}

program iso7185prt0716;

var b: boolean;

begin

   b := 1 => 2

end.
)plang").Ok);
}
