// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0027) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 27: Missing "=" in type

}

program iso7185prt0027(output);

type  integer char;

var i: integer;

begin

   writeln(i)

end.
)plang").Ok);
}
