// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0033) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 33: Missing var right side

}

program iso7185prt0033;

var  store;

begin

   writeln(store)

end.
)plang").Ok);
}
