// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0050) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 50: Misspelled function

}

program iso7185prt0050(output);

funktion x: integer; begin end;

begin

   writeln(x)

end.
)plang").Ok);
}
