// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0606) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 606: Missing parameter specification after 'var'

}

program iso7185prt0606;

var b: integer;

procedure a(var );

begin
end;

begin

   a(b)

end.
)plang").Ok);
}
