// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0906) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 906: Fraction with missing value

}

program iso7185prt0906(output);

begin

    
   write(1.0:2: )

end.
)plang").Ok);
}
