// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0117) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 117: Missing expression on case statement

}

program iso7185prt0117;

var a: integer;

begin

   case of 

      1: a := 1;
      2: a := 2

   end

end.
)plang").Ok);
}
