// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0900) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 900: Empty list (parens only)

}

program iso7185prt0900(output);

begin

    
   write()

end.
)plang").Ok);
}
