// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0515) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 515: Missing type on file type

}

program iso7185prt0515;

var a: file of;

begin

   rewrite(a)

end.
)plang").Ok);
}
