// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0132) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 132: Missing "until" on repeat statement

}

program iso7185prt0132;

var a, b: integer;

begin

   repeat a := b a = b

end.
)plang").Ok);
}
