// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0605) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 605: Missing type identifier on parameter specification

}

program iso7185prt0605;

procedure a(b, c:);

begin

   b := 1;
   c := 1

end;

begin

   a(1,2)

end.
)plang").Ok);
}
