// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0126) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 126: Missing "while" on while statement

}

program iso7185prt0126;

var a, b: integer;

begin

   1=1 do a := b

end.
)plang").Ok);
}
