// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0002) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 2: missing "program" word-symbol

}

iso7185prt0002

begin
end.
)plang").Ok);
}
