// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0025) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 25: Missing type

}

program iso7185prt0025;

type ;

begin
end.
)plang").Ok);
}
