// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0128) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 128: Missing expression on while statement 

}

program iso7185prt0128;

var a, b: integer;

begin

   while do a := b

end.
)plang").Ok);
}
