// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0003) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 3: missing program name word-symbol

}

program;

begin
end.
)plang").Ok);
}
