// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0102) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 102: Missing assignment left side

}

program iso7185prt0102;

begin

   := 5

end.
)plang").Ok);
}
