// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0708) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 708: Missing second operand to '<>'

}

program iso7185prt0708;

var b: boolean;

begin

   b := 1 <>

end.
)plang").Ok);
}
