// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0509) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 509: Missing 'of' on array

}

program iso7185prt0509;

var a: array [1..10] integer;

begin

   a[1] := 1

end.
)plang").Ok);
}
