// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0150) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 150: Missing second variable in with statement list

}

program iso7185prt0150;

var a: record b, c: integer end;
    d: record e, f: integer end;

begin

   with d, do e := f

end.
)plang").Ok);
}
