// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0520) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 520: Misspelled 'record' on field list

}

program iso7185prt0520;

var a: recard a, b: integer end;

begin

   a.a := 1

end.
)plang").Ok);
}
