// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0040) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 40: Reverse order between type and var

}

program iso7185prt0040(output);

var   one: integer;

type  integer = char;

begin

   writeln(one)

end.
)plang").Ok);
}
