// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0039) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 39: Missing semicolon in var

}

program iso7185prt0039(output);

var  one: char
     two: integer;

begin

   writeln(one, two)

end.
)plang").Ok);
}
