// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0714) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 714: Alternate '><'

}

program iso7185prt0714;

var b: boolean;

begin

   b := 1 >< 2

end.
)plang").Ok);
}
