// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0100) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 100: Missing label ident

}

program iso7185prt0100;

begin

   : if 1=1 then

end.
)plang").Ok);
}
