// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0151) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 151: Missing "goto" in goto statement

}

program iso7185prt0151;

label 1;

begin

   1

   1:;

end.
)plang").Ok);
}
