// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0012) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 12: Consecutive semicolons

}

program iso7185prt0012;;

begin
end.
)plang").Ok);
}
