// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0208) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 208: Missing type identifier with field identifier

}

program iso7185prt0208;

var a: record b, c: integer;
              case d: of
                 true: ();
                 false: ()
       end;

begin

   a.b := 1

end.
)plang").Ok);
}
