// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0118) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 118: Missing "of" on case statement

}

program iso7185prt0118;

var x, a: integer;

begin

   case x 

      1: a := 1;
      2: a := 2

   end

end.
)plang").Ok);
}
