// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0139) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 139: Missing ":=" on for statement

}

program iso7185prt0139;

var i, a, b: integer;

begin

   for i 1 to 10 do a := b

end.
)plang").Ok);
}
