// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0907) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 907: Field and fraction with missing field

}

program iso7185prt0907(output);

begin

    
   write(1.0: :3)

end.
)plang").Ok);
}
