// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0030) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 30: Missing semicolon in type

}

program iso7185prt0030;

type  integer = char
      five = integer;

var i: integer;
    a: five;

begin

   i := 'a';
   a := 1

end.
)plang").Ok);
}
