// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0157) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 157: Missing ',' between variables in with statement

}

program iso7185prt0157;

var a: record b, c: integer end;
    d: record e, f: integer end;

begin

   with a d do e := f

end.
)plang").Ok);
}
