// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0116) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 116: Misspelled "case" on case statement

}

program iso7185prt0116;

var x, a: integer;

begin

   csae x of 

      1: a := 1;
      2: a := 2

   end

end.
)plang").Ok);
}
