// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0156) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 156: Missing ',' between case constants

}

program iso7185prt0156;

var x, a: integer;

begin

   case x of

      1 2: a := 1;
      3: a := 2

   end

end.
)plang").Ok);
}
