// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0506) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 506: Missing second index in array

}

program iso7185prt0506;

var a: array [1..] of integer;

begin

   a[1] := 1

end.
)plang").Ok);
}
