// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0155) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 155: Missing only variable in with statement list

}

program iso7185prt0155;

var a: record b, c: integer end;
    d: record e, f: integer end;

begin

   a.b := 1;
   with do e := f

end.
)plang").Ok);
}
