// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0013) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 13: Missing number for label

}

program iso7185prt0013;

label;

begin
end.
)plang").Ok);
}
