// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0514) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 514: Missing 'of' on file type

}

program iso7185prt0514;

var a: file integer;

begin

   rewrite(a)

end.
)plang").Ok);
}
