// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0140) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 140: Missing start expression on for statement

}

program iso7185prt0140;

var i, a, b: integer;

begin

   for i := to 10 do a := b

end.
)plang").Ok);
}
