// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0119) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 119: Misspelled "of" on case statement

}

program iso7185prt0119;

var x, a: integer;

begin

   case x fo

      1: a := 1;
      2: a := 2

   end

end.
)plang").Ok);
}
