// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0120) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 120: Missing constant on case stament list

}

program iso7185prt0120;

var x, a: integer;

begin

   case x of

      : a := 1;
      2: a := 2

   end

end.
)plang").Ok);
}
