// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0035) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 35: Missing type var ident list follow

}

program iso7185prt0035(output);

var one, : integer;

begin

   writeln(one)

end.
)plang").Ok);
}
