// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0143) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 143: Misspelled "downto" on for statement

}

program iso7185prt0143;

var i, a, b: integer;

begin

   for i := 10 dunto 1 do a := b

end.
begin
.
)plang").Ok);
}
