// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0511) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 511: Missing type on array

}

program iso7185prt0511;

var a: array [1..10] of;

begin

   a[1] := 1

end.
)plang").Ok);
}
