// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0129) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 129: Missing "do" on while statement

}

program iso7185prt0129;

var a, b: integer;

begin

   while 1=1 a := b

end.
)plang").Ok);
}
