// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0109) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 109: Missing "if" on conditional

}

program iso7185prt0109;

begin

   1=1 then

end.
)plang").Ok);
}
