// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0112) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 112: Missing "then" on conditional

}

program iso7185prt0112;

var a, b: integer;

begin

   if 1=1 a := b

end.
)plang").Ok);
}
