// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0051) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 51: Bad procedure/function

}

program iso7185prt0051;

bark x; begin end;

begin
end.
)plang").Ok);
}
