// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0221) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 221: Missing ',' between first and second field idents

}

program iso7185prt0221;

var a: record b c: integer end;

begin

   a.b := 1

end.
)plang").Ok);
}
