// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0522) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 522: Misspelled 'end' on field list

}

program iso7185prt0522;

var a: record a, b: integer den;

begin

   a.a := 1

end.
)plang").Ok);
}
