// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0056) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 56: missing begin word-symbol

}

program iso7185prt0056;

end.
)plang").Ok);
}
