// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0134) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 134: Missing expression on repeat statement

}

program iso7185prt0134;

var a, b: integer;

begin

   repeat a := b until

end.
)plang").Ok);
}
