// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0101) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 101: Missing label ":"

}

program iso7185prt0101;

label 1;

begin

   goto 1;

   1 if 1=1 then

end.
)plang").Ok);
}
