// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0901) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 901: Missing leading '(' in list

}

program iso7185prt0901(output);

begin

    
   write 42)

end.
)plang").Ok);
}
