// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0519) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 519: Missing 'record' on field list

}

program iso7185prt0519;

var a: a, b: integer end;

begin

   a.a := 1

end.
)plang").Ok);
}
