// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0044) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 44: Consecutive semicolons start

}

program iso7185prt0044;

procedure x;; begin end;

begin

   x

end.
)plang").Ok);
}
