// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0211) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 211: Misspelled 'of' on variant

}

program iso7185prt0211;

var a: record b, c: integer;
              case d: boolean fo
                 true: ();
                 false: ()
       end;

begin

   a.b := 1

end.
)plang").Ok);
}
