// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0408) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 408: Missing ',' between identifiers on enumeration

}

program iso7185prt0408;

var a: (one two);

begin

   a := one

end.
)plang").Ok);
}
