// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0038) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 38: Incomplete second in var

}

program iso7185prt0038(output);

var  one: char;
     two;

begin

   writeln(one, two)

end.
)plang").Ok);
}
