// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0037) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 37: Missing ident list in var

}

program iso7185prt0037;

var : integer;

begin
end.
)plang").Ok);
}
