// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0020) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 20: Missing "=" in const

}

program iso7185prt0020(output);

const one 1;

begin

   writeln(one)

end.
)plang").Ok);
}
