// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0222) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 222: Missing ',' between first and second field idents in variant

}

program iso7185prt0222;

type q = (one, two, three);

var a: record b, c: integer;
              case d: q of
                 one two: ();
                 three: ()
       end;

begin

   a.b := 1

end.
)plang").Ok);
}
