// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0207) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 207: Missing identifier for variant

}

program iso7185prt0207;

var a: record b, c: integer;
              case : boolean of
                 true: ();
                 false: ()
       end;

begin

   a.b := 1

end.
)plang").Ok);
}
