// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0124) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 124: Missing "end" on case statement

}

program iso7185prt0124;

var x, a: integer;

begin

   case x of

      1: a := 1;
      2: a := 2

end.
)plang").Ok);
}
