// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0032) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 32: Missing var

}

program iso7185prt0032;

var ;

begin
end.
)plang").Ok);
}
