// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0218) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 218: Missing ';' between successive variant cases

}

program iso7185prt0218;

type q = (one, two, three);

var a: record b, c: integer;
              case d: q of
                 one, two: ()
                 three: ()
       end;

begin

   a.b := 1

end.
)plang").Ok);
}
