// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0903) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 903: Missing first parameter in parameter list

}

program iso7185prt0903(output);

begin

    
   write(, 84)

end.
)plang").Ok);
}
