// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0001) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1: missing semicolon after program statement

}

program iso7185prt0001

begin
end.
)plang").Ok);
}
