// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0147) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 147: Missing "with" on with statement

}

program iso7185prt0147;

var a: record b, c: integer end;

begin

   a do b := c

end.
)plang").Ok);
}
