// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0036) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 36: Missing ":" in var

}

program iso7185prt0036(output);

var one integer;

begin

   writeln(one)

end.
)plang").Ok);
}
