// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0209) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 209: Missing type identifier without field identifier

}

program iso7185prt0209;

var a: record b, c: integer;
              case of
                 true: ();
                 false: ()
       end;

begin

   a.b := 1

end.
)plang").Ok);
}
