// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0500) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 500: Missing type identifer after '^'

}

program iso7185prt0500;

var a: ^;

begin

   a := nil

end.
)plang").Ok);
}
