// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0402) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 402: Missing 1st identifier on enumeration

}

program iso7185prt0402;

var a: (, two);

begin

   a := two

end.
)plang").Ok);
}
