// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0142) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 142: Misspelled "to" on for statement

}

program iso7185prt0142;

var i, a, b: integer;

begin

   for i := 1 ta 10 do a := b

end.
)plang").Ok);
}
