// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0700) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 700: Missing operator

}

program iso7185prt0700;

var b: boolean;

begin

   b := 1 2

end.
)plang").Ok);
}
