// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0302) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 302: Missing procedure identifier

}

program iso7185prt0302;

procedure (one, two: integer);

begin

   one := 1;
   two := 2

end;

begin

end.
)plang").Ok);
}
