// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0600) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 600: Missing parameter identifier

}

program iso7185prt0600;

procedure a(: integer);

begin
end;

begin

   a(1)

end.
)plang").Ok);
}
