// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0127) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 127: Mispelled "while" on while statement

}

program iso7185prt0127;

var a, b: integer;

begin

   wihle 1=1 do a := b

end.
)plang").Ok);
}
