// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0503) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 503: Missing '[' on array

}

program iso7185prt0503;

var a: array 1..10] of integer;

begin

   a[1] := 1

end.
)plang").Ok);
}
