// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0205) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 205: Missing ';' between successive fields

}

program iso7185prt0205;

var a: record b, c: integer end
    d: record e, f: integer end;

begin

   a.b := 1;
   d.e := 1

end.
)plang").Ok);
}
