// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0303) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 303: Missing 'function'

}

program iso7185prt0303;

x(one, two: integer): char;

begin

   x := 'a'

end;

begin

end.
)plang").Ok);
}
