// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0305) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 305: Missing function identifier

}

program iso7185prt0305;

function (one, two: integer): char;

begin

   one := 1;
   two := 2;
   x := 'a'

end;

begin

end.
)plang").Ok);
}
