// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0053) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 53: Missing type id on return type for function

}

program iso7185prt0053;

function x: ; begin x := 1 end;

begin
end.
)plang").Ok);
}
