// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0008) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 8: Missing header parameters

}

program iso7185prt0008();

begin
end
)plang").Ok);
}
