// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0602) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 602: Missing second parameter identifier

}

program iso7185prt0602;

procedure a(b,: integer);

begin

   b := 1

end;

begin

   a(1, 2)

end.
)plang").Ok);
}
