// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0300) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 300: Missing 'procedure'

}

program iso7185prt0300;

x(one, two: integer);

begin
end;

begin

end.
)plang").Ok);
}
