// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0146) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 146: Misspelled "do" on for statement

}

program iso7185prt0146;

var i, a, b: integer;

begin

   for i := 1 to 10 od a := b

end.
)plang").Ok);
}
