// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0022) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 22: Missing ident in const

}

program iso7185prt0022;

const = 1;


begin
end.
)plang").Ok);
}
