// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0130) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 130: Missing "repeat" on repeat statement

}

program iso7185prt0130;

var a, b: integer;

begin

   a := b until a = b

end.
)plang").Ok);
}
