// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0046) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 46: Missing final semicolon

}

program iso7185prt0046;

procedure x; begin end

begin

   x

end.
)plang").Ok);
}
