// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0048) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 48: Bad directive

}

program iso7185prt0048;

procedure x; bark;

begin

   x

end.
)plang").Ok);
}
