// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0024) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 24: Reverse order between label and const

}

program iso7185prt0024(output);

const one = 1;

label 1;

begin

   writeln(one);

   goto 1;

   1:

end.
)plang").Ok);
}
