// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0108) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 108: Mispelled "end" on statement block

}

program iso7185prt0108;

begin

   begin

      if 1=1 then

   edn

end.
)plang").Ok);
}
