// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0712) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 712: Missing second operand to '>='

}

program iso7185prt0712;

var b: boolean;

begin

   b := 1 >=

end.
)plang").Ok);
}
