// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0041) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 41: Missing "procedure" or "function"

}

program iso7185prt0041;

x; begin end;

begin
end.
)plang").Ok);
}
