// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0516) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 516: Misspelled 'set' on set type

}

program iso7185prt0516;

var a: ste of char;

begin

   a := []

end.
)plang").Ok);
}
