// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0214) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 214: Missing second constant on variant

}

program iso7185prt0214;

type q = (one, two, three);

var a: record b, c: integer;
              case d: q of
                 one,: ();
                 three: ()
       end;

begin

   a.b := 1

end.
)plang").Ok);
}
