// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0007) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 7: Extra semicolon

}

program iso7185prt0007;;

begin
end
)plang").Ok);
}
