// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0131) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 131: Misspelled "repeat" on repeat statement

}

program iso7185prt0131;

var a, b: integer;

begin

   reepat a := b until a = b

end.
)plang").Ok);
}
