// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0106) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 106: Misspelled "begin" on statement block

}

program iso7185prt0106;

begin

   beign

      if 1=1 then

   end

end.
)plang").Ok);
}
