// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0908) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 908: Missing ')' in list

}

program iso7185prt0908(output);

begin

    
   write(42

end.
)plang").Ok);
}
