// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0107) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 107: Missing "end" on statement block

}

program iso7185prt0107;

begin

   begin

      if 1=1 then

end.
)plang").Ok);
}
