// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0031) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 31: Reverse order between const and type

}

program iso7185prt0031(output);

type  integer = char;

const one = 1;

var i: integer;

begin

   i := 'a';
   writeln(one, i)

end.
)plang").Ok);
}
