// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0400) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 400: Missing '(' on enumeration

}

program iso7185prt0400;

var a: one, two, three);

begin

   a := one;
   a := two;
   a := three

end.
)plang").Ok);
}
