// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0018) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 18: Missing constant

}

program iso7185prt0018;

const;

begin
end.
)plang").Ok);
}
