// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0034) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 34: Missing type var ident list prime

}

program iso7185prt0034(output);

var , two: integer;

begin

   writeln(two)

end.
)plang").Ok);
}
