// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0011) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 11: Improperly terminated header list

}

program iso7185prt0011(output,);

begin
end
)plang").Ok);
}
