// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0513) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 513: Misspelled 'file' on file type

}

program iso7185prt0513;

var a: filed of integer;

begin

   rewrite(a)

end.
)plang").Ok);
}
