// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0023) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 23: Missing semicolon in const

}

program iso7185prt0023(output);

const one = 1
      two = 2;

begin

   writeln(one, two)

end.
)plang").Ok);
}
