// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0114) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 114: Misspelled "else" on conditional

}

program iso7185prt0114;

var a, b: integer;

begin

   if 1=1 then a := b eles b := a

end.
)plang").Ok);
}
