// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0055) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 55: Reverse order between var and function

}

program iso7185prt0055(output);

function x: integer; begin x := 1 end;

var y: integer;

begin

   writeln(x, y)

end.
)plang").Ok);
}
