// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0401) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 401: Missing identifier on enumeration

}

program iso7185prt0401;

var a: ();

begin

   a := one

end.
)plang").Ok);
}
