// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0510) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 510: Misspelled 'of' on array

}

program iso7185prt0510;

var a: array [1..10] fo integer;

begin

   a[1] := 1

end.
)plang").Ok);
}
