// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0006) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 6: missing period

}

program iso7185prt0006;

begin
end
)plang").Ok);
}
