// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0152) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 152: Misspelled "goto" in goto statement

}

program iso7185prt0152;

label 1;

begin

   ogto 1;

   1:;

end.
)plang").Ok);
}
