// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0113) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 113: Misspelled "then" on conditional

}

program iso7185prt0113;

var a, b: integer;

begin

   if 1=1 thne a := b

end.
)plang").Ok);
}
