// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0206) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 206: Misspelled 'case' to variant

}

program iso7185prt0206;

var a: record b, c: integer;
              csae d: boolean of
                 true: ();
                 false: ()
       end;

begin

   a.b := 1

end.
)plang").Ok);
}
