// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0019) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 19: Missing constant right side

}

program iso7185prt0019(output);

const one;

begin

   writeln(one)

end.
)plang").Ok);
}
