// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0026) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 26: Missing type right side

}

program iso7185prt0026(output);

type  integer;

var i: integer;

begin

   writeln(i)

end.
)plang").Ok);
}
