// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0125) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 125: Misspelled "end" on case statement

}

program iso7185prt0125;

var x, a: integer;

begin

   case x of

      1: a := 1;
      2: a := 2

   edn

end.
)plang").Ok);
}
