// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0045) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 45: Missing block

}

program iso7185prt0045;

procedure x; ;

begin

   x

end.
)plang").Ok);
}
