// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0517) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 517: Missing 'of' on set type

}

program iso7185prt0517;

var a: set char;

begin

   a := []

end.
)plang").Ok);
}
