// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0148) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 148: Misspelled "with" on with statement

}

program iso7185prt0148;

var a: record b, c: integer end;

begin

   wtih a do b := c

end.
)plang").Ok);
}
