// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0028) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 28: Missing ident in type

}

program iso7185prt0028;

type  = char;

begin
end.
)plang").Ok);
}
