// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0212) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 212: Missing case constant on variant

}

program iso7185prt0212;

var a: record b, c: integer;
              case d: boolean of
                 : ();
                 false: ()
       end;

begin

   a.b := 1

end.
)plang").Ok);
}
