// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0804) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 804: Missing second parameter in parameter list

}

program iso7185prt0804;

procedure test(a, b: integer);

begin

   a := 1;
   b := 1

end;

begin

   test(1, )

end.
)plang").Ok);
}
