// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0204) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 204: Missing type

}

program iso7185prt0204;

var a: record b: end;

begin

   a.b := 1

end.
)plang").Ok);
}
