// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0153) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 153: Missing unsigned integer in goto statement

}

program iso7185prt0153;

{ Theoretically the compiler could determine that only one label is possible,
  and use that to recover. }
label 1;

begin

   goto ;

   1:

end.
)plang").Ok);
}
