// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0103) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 103: Missing assignment ":="

}

program iso7185prt0103;

var a: integer;

begin

   a 1

end.
)plang").Ok);
}
