// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0502) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 502: Missing 'array'

}

program iso7185prt0502;

var a: [1..10] of integer;

begin

   a[1] := 1

end.
)plang").Ok);
}
