// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0508) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 508: Missing index specification in array

}

program iso7185prt0508;

var a: array of integer;

begin

   a[1] := 1

end.
)plang").Ok);
}
