// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0029) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 29: Incomplete second in type

}

program iso7185prt0029(output);

type  integer = char;
      five;

var c: integer;
    d: five;

begin

   c := 'a';
   d := 1;
   writeln(c, d)

end.
)plang").Ok);
}
