// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0016) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 16: Unterminated label list

}

program iso7185prt0016;

label 1,;

begin

   goto 1;

   1:

end.
)plang").Ok);
}
