// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0902) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 902: Missing ',' in parameter list

}

program iso7185prt0902(output);

begin

    
   write(42 84)

end.
)plang").Ok);
}
