// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0049) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 49: Misspelled procedure

}

program iso7185prt0049;

prosedure x; begin end;

begin

   x

end.
)plang").Ok);
}
