// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0137) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 137: Missing variable ident on for statement

}

program iso7185prt0137;

var i, a, b: integer;

begin

   for := 1 to 10 do a := b

end.
)plang").Ok);
}
