// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0717) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 717: Missing first operand to 'in'

}

program iso7185prt0717;

var b: boolean;

begin

   b := in [1..6]

end.
)plang").Ok);
}
