// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0905) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 905: Field with missing value

}

program iso7185prt0905(output);

begin

    
   write(84: )

end.
)plang").Ok);
}
