// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0800) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 800: Empty list (parens only)

}

program iso7185prt0800;

procedure test(a, b: integer);

begin

   a := 1;
   b := 1

end;

begin

   test()

end.
)plang").Ok);
}
