// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0111) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 111: Missing expression on conditional

}

program iso7185prt0111;

var a, b: integer;

begin

   if then a := b

end.
)plang").Ok);
}
