// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0203) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 203: Missing ':' between ident and type

}

program iso7185prt0203;

var a: record b integer end;

begin

   a.b := 1

end.
)plang").Ok);
}
