// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0607) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 607: Misspelled 'var'

}

program iso7185prt0607;

var b: integer;

procedure a(vas b: integer);

begin

   b := 1

end;

begin

   a(b)

end.
)plang").Ok);
}
