// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0405) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 405: Missing 1st constant on subrange

}

program iso7185prt0405;

var a: ..5;

begin

   a := 1

end.
)plang").Ok);
}
