// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0200) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 200: Missing field ident

}

program iso7185prt0200;

var a: record : integer end;

begin

   with a do

end.
)plang").Ok);
}
