// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0141) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 141: Missing "to"/"downto" on for statement

}

program iso7185prt0141;

var i, a, b: integer;

begin

   for i := 10 1 do a := b

end.
)plang").Ok);
}
