// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0144) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 144: Missing end expression on for statement

}

program iso7185prt0144;

var i, a, b: integer;

begin

   for i := 1 to do a := b

end.
)plang").Ok);
}
