// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0505) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 505: Missing first index in array

}

program iso7185prt0505;

var a: array [..10] of integer;

begin

   a[1] := 1

end.
)plang").Ok);
}
