// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0054) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 54: Reverse order between var and procedure

}

program iso7185prt0054(output);

procedure x; begin end;

var y: integer;

begin

   x;
   writeln(y)

end.
)plang").Ok);
}
