// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0105) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 105: Missing "begin" on statement block

}

program iso7185prt0105;

var a, b: integer;

begin

      if 1=1 then a := b

   end

end.
)plang").Ok);
}
