// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0052) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 52: Missing ":"on return type for function

}

program iso7185prt0052;

function x integer; begin x := 1 end;

begin
end.
)plang").Ok);
}
