// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0202) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 202: Missing second field ident

}

program iso7185prt0202;

var a: record b,: integer end;

begin

   a.b := 1

end.
)plang").Ok);
}
