// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0406) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 406: Missing '..' on subrange

}

program iso7185prt0406;

var a: 1 5;

begin

   a := 1

end.
)plang").Ok);
}
