// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0407) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 407: Missing 2nd constant on subrange

}

program iso7185prt0155;

var a: 1..;

begin

   a := 1

end.
)plang").Ok);
}
