// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0057) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 57: missing end word-symbol

}

program iso7185prt0057;

begin
.
)plang").Ok);
}
