// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0403) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 403: Missing 2nd identifier on enumeration

}

program iso7185prt0403;

var a: (one, );

begin

   a := one

end.
)plang").Ok);
}
