// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0521) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 521: Missing 'end' on field list

}

program iso7185prt0521;

var a: record a, b: integer;

begin

   a.a := 1

end.
)plang").Ok);
}
