// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0512) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 512: Missing 'file' or 'set' on file or set type

}

program iso7185prt0512;

var a: of integer;

begin

   a := []

end.
)plang").Ok);
}
