// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0110) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 110: Misspelled "if" on conditional 

}

program iso7185prt0110;

begin

   fi 1=1 then

end.
)plang").Ok);
}
