// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0009) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 9: Opening paren for program header only

}

program iso7185prt0009(;

begin
end
)plang").Ok);
}
