// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0042) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 42: Missing ident

}

program iso7185prt0042;

procedure ; begin end;

begin
end.
)plang").Ok);
}
