// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0021) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 21: Incomplete second in const

}

program iso7185prt0021(output);

const one = 1;
      two;

begin

   writeln(one, two)

end.
)plang").Ok);
}
