// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0518) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 518: Missing type on set type

}

program iso7185prt0518;

var a: set of;

begin

   a := []

end.
)plang").Ok);
}
