// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0604) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 604: Missing ':' on parameter specification

}

program iso7185prt0604;

procedure a(b, c integer);

begin

   b := 1;
   c := 1

end;

begin

   a(1, 2)

end.
)plang").Ok);
}
