// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0501) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 501: Misspelled 'packed'

}

program iso7185prt0501;

var a: picked array [1..10] of integer;

begin

   a[1] := 1

end.
)plang").Ok);
}
