// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt0601) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 601: Missing first parameter identifier

}

program iso7185prt0601;

procedure a(, c: integer);

begin

   c := 1

end;

begin

   a(1, 2)

end.
)plang").Ok);
}
