// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1407) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1407: Missing field identifier after '.'

}

program iso7185prt1407(output);

var a: integer;
    b: record one, two: integer end;

begin

   a := b.

end.
)plang").Ok);
}
