// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceClean, prt1731) {
    EXPECT_TRUE(check(R"plang(
{

PRT test 1731: For unpack, it is an error if the index-type of the unpacked 
               array is exceeded.

               ISO 7185 reference: 6.6.5.4

}

program iso7185prt1731;

var a: array [1..10] of integer;
    b: packed array [1..10] of integer;

begin

   unpack(b, a, 5)

end.
)plang").Ok);
}
