// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1621) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1621: Comment end only.

}

program iso7185prt1621;

begin

   }

end.
)plang").Ok);
}
