// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1006) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1006: Missing first expression in range

}

program iso7185prt1006(output);

var a, b: integer;

begin

   a := b in [..10]

end.
)plang").Ok);
}
