// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1400) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1400: Missing variable or field identifier

}

program iso7185prt1400(output);

var a: integer;
    b: ^integer;

begin

   a := ^

end.
)plang").Ok);
}
