// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1500) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1500: Missing leading digit before '.'

}

program iso7185prt1500(output);

var a: integer;

begin

   a := .5

end.
)plang").Ok);
}
