// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1748) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1748: It is an error if the result of an activation of a function is
               undefined upon completion of the algorithm of the activation.

               ISO 7185 reference: 6.7.3

}

program iso7185prt1748(output);

function a: integer;

begin

end;

begin

   write(a)

end.
)plang").Ok);
}
