// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceClean, prt1723) {
    EXPECT_TRUE(check(R"plang(
{

PRT test 1723: For dispose, it is an error if the parameter of a pointer-type
               has a nil-value.

               ISO 7185 reference: 6.6.5.3

}

program iso7185prt1723(output);

var a: ^integer;

begin

   a := nil;
   dispose(a)

end.
)plang").Ok);
}
