// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1007) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1007: Missing second expression in range

}

program iso7185prt1007(output);

var a, b: integer;

begin

   a := b in [1..]  

end.
)plang").Ok);
}
