// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceClean, prt1852) {
    EXPECT_TRUE(check(R"plang(
{

PRT test 1852: Out of range for index variable

   Test if out of range is checked on 'for' index variable.


}

program iso7185prt1852(output);

var i: 1..9;


begin

   for i := 0 to 10 do writeln('i: ', i)

end.
)plang").Ok);
}
