// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1846) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1846: Numeric overflow on constant

    Integer overflow.

}

program iso7185prt1846(output);

begin

   write(100000000000000000000000000000000000000000000000000000000000000)

end.
)plang").Ok);
}
