// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceClean, prt1733) {
    EXPECT_TRUE(check(R"plang(
{

PRT test 1733: For ln(x), it is an error if x is not greater than zero.

               ISO 7185 reference: 6.6.5.2

}

program iso7185prt1733;

var a: integer;
    r: real;

begin

   a := 0;
   r := ln(a)

end.
)plang").Ok);
}
