// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1622) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1622: Nested comments

}

program iso7185prt1622;

begin

   { hi there (* george *) again... }

end.
)plang").Ok);
}
