// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1807) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1807: Threats to FOR statement index.

    Threat in same scope block, read or readln.
    ISO 7185 6.8.3.9

}

program iso7185prt1807(output);

var i: integer;
    f: file of integer;

procedure a;

begin

   read(f, i)

end;

begin

   rewrite(f);
   write(f, 10);
   reset(f);
   for i := 1 to 10 do begin

      write(i:1, ' ')

   end;
   a

end.
)plang").Ok);
}
