// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1108) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1108: Missing first operand to 'and'

}

program iso7185prt1108(output);

var a, b: boolean;

begin

   a := and b 

end.
)plang").Ok);
}
