// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1010) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1010: Missing second expression in ',' delimited set constant list

}

program iso7185prt1010(output);

var a, b: integer;

begin

   a := b in [1, ]

end.
)plang").Ok);
}
