// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1826) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1826: Files of files

    Direct specification of file of file.
    ISO 7185 6.4.3.5

}

program iso7185prt1826;

var f: file of file of integer;

begin

   rewrite(f)

end.
)plang").Ok);
}
