// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1842) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1842: Use of text procedure with non-text

    Use readln with integer file.
    ISO 7185 6.9.2

}

program iso7185prt1842(output);

var f: file of integer;
    i: integer;

begin

   rewrite(f);
   write(f, 1);
   reset(f);
   readln(f, i)

end.
)plang").Ok);
}
