// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1104) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1104: Missing first operand to 'div'

}

program iso7185prt1104(output);

var a, b: integer;

begin

   a := div b  

end.
)plang").Ok);
}
