// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1831) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1831: Parameter type mismatch

    Wrong type of a parameter.
    ISO 7185 6.8.2.3

}

program iso7185prt1831;

procedure a(b: integer; c: char);

begin

   b := 1;
   c := 'a'

end;

begin

   a(1, 2)

end.
)plang").Ok);
}
