// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1503) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1503: Mispelled 'e' in exponent

}

program iso7185prt1503(output);

var a: integer;

begin

   a := 1d5

end.
)plang").Ok);
}
