// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1406) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1406: Missing ']' in index list

}

program iso7185prt1406(output);

var a: integer;
    b: array [1..10] of integer;

begin

   a := b[5

end.
)plang").Ok);
}
