// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1600) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1600: String extends beyond eol (no end quote)

}

program iso7185prt1600(output);

begin

   writeln('Hello, world)

end.
)plang").Ok);
}
