// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1003) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1003: 'not' missing expression

}

program iso7185prt1003(output);

var a: boolean;

begin

   a := not

end.
)plang").Ok);
}
