// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1200) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1200: '+' with missing term

}

program iso7185prt1200(output);

var a: integer;

begin

   a := +  

end.
)plang").Ok);
}
