// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceClean, prt1704) {
    EXPECT_TRUE(check(R"plang(
{

PRT test 1704: It is an error if the pointer-variable of an 
               identified-variable is undefined.

               ISO 7185 reference: 6.5.4

}

program iso7185prt1704(output);

var a: ^integer;
    b: integer;

begin

   b := a^

end.
)plang").Ok);
}
