// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1822) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1822: Double definitions

    Double define with different case.
    ISO 7185 6.2.2.7

}

program iso7185prt1822(output);

var myvar: integer;
    MyVar: integer;

begin

   writeln(myvar)

end.
)plang").Ok);
}
