// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1841) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1841: Zero length string

    Write zero length string.

}

program iso7185prt1841(output);

begin

   writeln('')

end.
)plang").Ok);
}
