// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1821) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1821: Double definitions

    Double define with same type.
    ISO 7185 6.2.2.7

}

program iso7185prt1821(output);

var i: integer;
    i: integer;

begin

   writeln(i)

end.
)plang").Ok);
}
