// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceClean, prt1850) {
    EXPECT_TRUE(check(R"plang(
{

PRT test 1850: Unreferenced variable

   Variable without reference in program. Note that this is technically not an
   error. Its just a compiler quality test if it can detect this.

}

program iso7185prt1850;

var i: integer;

begin

end.
)plang").Ok);
}
