// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1009) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1009: Missing first expression in ',' delimited set constant list

}

program iso7185prt1009(output);

var a, b: integer;

begin

   a := b in [ , 2]  

end.
)plang").Ok);
}
