// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1508) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1508: Missing number before exponent

}

program iso7185prt1508(output);

var a: integer;

begin

   { somewhat ambiguous, could be "e" as identifier }
   a := e+5

end.
)plang").Ok);
}
