// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceClean, prt1705) {
    EXPECT_TRUE(check(R"plang(
{

PRT test 1705: It is an error to remove from its pointer-type the
               identifying-value of an identified-variable when a reference to
               the identified-variable exists.

               ISO 7185 reference: 6.5.4

}

program iso7185prt1705(output);

var a: ^integer;

procedure b(var c: integer);

begin

   c := 1;
   a := nil

end;

begin

   { allocate integer value and pass that as reference, then change the value
     of the pointer }
   new(a);
   b(a^)

end.
)plang").Ok);
}
