// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1106) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1106: Missing first operand to 'mod'

}

program iso7185prt1106(output);

var a, b: integer;

begin

   a := mod b

end.
)plang").Ok);
}
