// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1504) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1504: Missing 'e' in exponent

}

program iso7185prt1504(output);

var a: integer;

begin

   { somewhat ambiguous, could be a number of missing tolkens }
   a := 5 5

end.
)plang").Ok);
}
