// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1107) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1107: Missing second operand to 'mod'

}

program iso7185prt1107(output);

var a, b: integer;

begin

   a := b mod  

end.
)plang").Ok);
}
