// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1203) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1203: Missing second operand to '+'

}

program iso7185prt1203(output);

var a: integer;

begin

   a := a+  

end.
)plang").Ok);
}
