// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1505) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1505: Missing digits in exponent

}

program iso7185prt1505(output);

var a: integer;

begin

   a := 5e

end.
)plang").Ok);
}
