// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1205) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1205: Missing second operand to '-'

}

program iso7185prt1205(output);

var a, b: integer;

begin

   a := a-  

end.
)plang").Ok);
}
