// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1001) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1001: Missing subexpression in '()'

}

program iso7185prt1001(output);

var a, b: integer;

begin

   a := ( )  

end.
)plang").Ok);
}
