// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceClean, prt1839) {
    EXPECT_TRUE(check(R"plang(
{

PRT test 1839: Write with invalid fields

    Write with zero field.
    ISO 7185 6.9.3

}

program iso7185prt1839(output);

var i: integer;

begin

   i := 1;
   writeln(i:0)

end.
)plang").Ok);
}
