// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1405) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1405: Missing ',' in index list

}

program iso7185prt1405(output);

var a: integer;
    b: array [1..10, 1..10] of integer;

begin

   a := b[5 6]  

end.
)plang").Ok);
}
