// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1201) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1201: '-' with missing term

}

program iso7185prt1201(output);

var a: integer;

begin

   a := -  

end.
)plang").Ok);
}
