// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1620) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1620: Unterminated comment

}

program iso7185prt1620;

begin

   {

end.
)plang").Ok);
}
