// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1100) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1100: Missing first operand to '*'

}

program iso7185prt1100(output);

var a, b: integer;

begin

   a := *b  

end.
)plang").Ok);
}
