// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceClean, prt1732) {
    EXPECT_TRUE(check(R"plang(
{

PRT test 1732: Sqr(x) computes the square of x. It is an error if such a value
               does not exist.

               ISO 7185 reference: 6.6.6.2

}

program iso7185prt1732;

var a: integer;

begin

   a := maxint;
   a := sqr(maxint)

end.
)plang").Ok);
}
