// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1838) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1838: Undefineds

    Undefined variable.

}

program iso7185prt1838;

begin

   i := 1

end.
)plang").Ok);
}
