// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1300) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1300: Misspelled 'nil'

}

program iso7185prt1300(output);

var a: ^integer;

begin

   a := nul  

end.
)plang").Ok);
}
