// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1507) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1507: Missing digits in exponent after '-'

}

program iso7185prt1507(output);

var a: integer;

begin

   a := 5e-

end.
)plang").Ok);
}
