// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1824) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1824: Invalid type substitutions

    Assign of real to integer.
    ISO 7185 6.6.3.3

}

program iso7185prt1824(input);

var i: integer;

begin

   i := 1.0

end.
)plang").Ok);
}
