// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1206) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1206: Missing first operand to 'or'

}

program iso7185prt1206(output);

var a, b: boolean;

begin

   a := or b  

end.
)plang").Ok);
}
