// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1105) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1105: Missing second operand to 'div'

}

program iso7185prt1105(output);

var a, b: integer;

begin

   a := b div  

end.
)plang").Ok);
}
