// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1904) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1904: If statement

    the condition part of an if statement must have boolean type
	ISO 7185 6.8.3.4

}

program iso7185prt1904(output);

type myBoolean = (myFalse, myTrue);

var b: myBoolean;

begin

   b := myTrue;
   if b then
      writeln('error not detected');

end.
)plang").Ok);
}
