// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1502) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1502: Missing digit before and after '.'

}

program iso7185prt1502(output);

var a: integer;

begin

   a := .

end.
)plang").Ok);
}
