// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1901) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1901: Constructing set from real

   Check attempt to construct set from real element.


}

program iso7185prt1901(output);

var
	r: real;

begin

    if [r] <> [] then

end.
)plang").Ok);
}
