// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1847) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1847: Numeric overflow on constant

    Overflow on exponent.

}

program iso7185prt1847(output);

begin

   write(1.0e100000000000000000000000000000000000000000000000000000000000000)

end.
)plang").Ok);
}
