// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1008) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1008: Missing '..' or ',' in set constant list

}

program iso7185prt1008(output);

var a, b: integer;

begin

   a := b in [1 10]

end.
)plang").Ok);
}
