// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceClean, prt1737) {
    EXPECT_TRUE(check(R"plang(
{

PRT test 1737: For chr(x), the function returns a result of char-type that is 
               the value whose ordinal number is equal to the value of the 
               expression x if such a character value exists. It is an error
               if such a character value does not exist.

               ISO 7185 reference: 6.6.5.3

}

program iso7185prt1737;

var a: integer;
    b: char;

begin

   a := -1;
   b := chr(a)

end.
)plang").Ok);
}
