// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1829) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1829: Parameter number mismatch

    Less parameters than specified.
    ISO 7185 6.8.2.3

}

program iso7185prt1829;

procedure a(b: integer; c: char);

begin

   b := 1;
   c := 'a'

end;

begin

   a(1)

end.
)plang").Ok);
}
