// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceClean, prt1724) {
    EXPECT_TRUE(check(R"plang(
{

PRT test 1724: For dispose, it is an error if the parameter of a pointer-type is
               undefined.

               ISO 7185 reference: 6.6.5.3

}

program iso7185prt1724(output);

var a: ^integer;

begin

   dispose(a)

end.
)plang").Ok);
}
