// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1004) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1004: Missing '[' on set constant

}

program iso7185prt1004(output);

var a, b: integer;

begin

   a := b in 1..10]

end.
)plang").Ok);
}
