// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1000) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1000: Missing leading '(' for subexpression

}

program iso7185prt1000(output);

var a, b: integer;

begin

   a := b)  

end.
)plang").Ok);
}
