// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1102) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1102: Missing first operand to '/'

}

program iso7185prt1102(output);

var a: real; 
    b: integer;

begin

   a := /b  

end.
)plang").Ok);
}
