// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1109) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1109: Missing second operand to 'and'

}

program iso7185prt1109(output);

var a, b: boolean;

begin

   a := a and

end.
)plang").Ok);
}
