// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1501) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1501: Missing digit after '.'

}

program iso7185prt1501(output);

var a: integer;

begin

   a := 5.

end.
)plang").Ok);
}
