// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1103) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1103: Missing second operand to '/'

}

program iso7185prt1103(output);

var a: real;
    b: integer;

begin

   a := b/

end.
)plang").Ok);
}
