// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1002) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1002: Misspelled 'not'

}

program iso7185prt1002(output);

var a, b: boolean;

begin

   a := nat b

end.
)plang").Ok);
}
