// Auto-generated by tools/gen_conformance_tests.py — DO NOT EDIT.
#include <gtest/gtest.h>
#include "TestHelper.h"
using namespace plang;

TEST(ConformanceError, prt1207) {
    EXPECT_FALSE(check(R"plang(
{

PRT test 1207: Missing second operand to 'or'

}

program iso7185prt1207(output);

var a, b: boolean;

begin

   a := a or  

end.
)plang").Ok);
}
